### PR TITLE
edited readme.md

### PR DESCRIPTION
**Pull request by pmontg04**

### CODE REVIEW

**Comment by pmontg04** [comment]
please approve me

**Comment by SkillBarrage** [comment]
3/10 at best

**Review by jackTeacup — CHANGES_REQUESTED** [review]
change please

**Comment by CodingStream** [comment]
This will suit the empire well

**Review by SkillBarrage — APPROVED** [review]

**Review by jackTeacup — APPROVED** [review]
ok

**Comment by jackTeacup** [comment]
NEVER

**Comment by CodingStream** [comment]
Its ok

**Review by CodingStream — APPROVED** [review]
Its cool

**Pull request merged**
