### PR TITLE
updated readme.md

### PR DESCRIPTION
**Pull request by jackTeacup**

### CODE REVIEW

**Comment by jackTeacup** [comment]
hi

**Comment by CodingStream** [comment]
NEVER!!!!!!!!

**Comment by pmontg04** [comment]
fine

**Comment by jackTeacup** [comment]
rude sir

**Comment by SkillBarrage** [comment]
The change is incorrect

**Review by CodingStream — APPROVED** [review]
fine

**Review by SkillBarrage — APPROVED** [review]

**Pull request merged**
